version: '2'

services:
  db:
    image: 'postgres'
    container_name: 'users-db'
    environment:
      - POSTGRES_PASSWORD=postgres

  app:
    image: 'alessandroamedei/user-service-florence:1'
    container_name: 'users-service'
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/postgres
    depends_on:
      - db
    ports:
      - "7001:7001"